---
title: "Final Presentation"
author: "Tony Segal"
date: "June 3, 2025"
format: pdf
---

```{r}
#| warning: false
#| message: false
#| echo: false

library(dplyr)
library(readr)
library(gt)
library(ggplot2)
library(estimatr)

bank <- read_csv("combined_fdic_data.csv")
```

```{r}
lbank <- read_csv("combined_fdic_data_log.csv")
```
```{r}
names(lbank)[10] <- "core_deposit"
lbank$State <- as.factor(lbank$State)
lbank$core_deposit <- as.numeric(lbank$core_deposit)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

lbank$west <- ifelse(lbank$State %in% c("California", "Oregon", "Arizona", "Nevada", "Washington", "Idaho", "Utah", "Montana", "Wyoming", "Colorado", "New Mexico"), 1, 0)
lbank$year <- format(lbank$Date, "%Y")
lbank$post <- ifelse(lbank$Date >= as.Date("2023-03-31"), 1, 0)
lbank$post <- as.factor(lbank$post)
lbank$west <- as.factor(lbank$west)

reg <- lm_robust(core_deposit ~ west + post + west*post, data = lbank, se_type = "HC1")
summary(reg)
```
```{r}
lbank$crash <- ifelse(lbank$west == 1 & lbank$post == 1, 1, 0)
lbank$Date <- as.factor(lbank$Date)

panel_reg <-lm_robust(core_deposit ~ crash + State + Date, data = lbank, se_type = "HC1")
summary(panel_reg)
```


```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Core Deposits to Total Liabilities"
#| label: tbl-core


#rename and change data types
names(bank)[10] <- "core_deposit"
bank$State <- as.factor(bank$State)
bank$core_deposit <- as.numeric(bank$core_deposit)
bank$Date <- as.Date(bank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- bank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for total core deposits by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_core_deposits = sum(core_deposit))

#get 2023 Q1 data for total core deposits by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_core_deposits = sum(core_deposit))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_core_deposits_q1_2023 - merged$total_core_deposits_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)


#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_core_deposits_q4_2022 = "2022 Q4",
    total_core_deposits_q1_2023 = "2023 Q1",
    diff = "Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_core_deposits_q4_2022, total_core_deposits_q1_2023, diff)
  )
  
# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Change in Core Deposits After Shock",
       x = "State",
       y = "Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Core Deposits to Total Liabilities"
#| label: tbl-log_core

lbank <- read_csv("combined_fdic_data_log.csv")


#rename and change data types
names(lbank)[10] <- "core_deposit"
lbank$State <- as.factor(lbank$State)
lbank$core_deposit <- as.numeric(lbank$core_deposit)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for total core deposits by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_core_deposits = sum(core_deposit))

#get 2023 Q1 data for total core deposits by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_core_deposits = sum(core_deposit))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_core_deposits_q1_2023 - merged$total_core_deposits_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)


#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_core_deposits_q4_2022 = "2022 Q4",
    total_core_deposits_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_core_deposits_q4_2022, total_core_deposits_q1_2023, diff)
  )
  
# print table 
gt_table

# Add bar graph
graph <- ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Core Deposits After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()

graph
ggsave("log_change_hist.png", plot = graph)
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Eearning Assets"
#| label: tbl-log_earning

#rename and change data types
names(lbank)[19] <- "earning_assets"
lbank$State <- as.factor(lbank$State)
lbank$earning_assets <- as.numeric(lbank$earning_assets)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for total earning assets by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_earning_assets = sum(earning_assets))

#get 2023 Q1 data for total earning assets by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_earning_assets = sum(earning_assets))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_earning_assets_q1_2023 - merged$total_earning_assets_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)


#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_earning_assets_q4_2022 = "2022 Q4",
    total_earning_assets_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_earning_assets_q4_2022, total_earning_assets_q1_2023, diff)
  )
  
# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Earning Assets After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Equity Capital"
#| label: tbl-log_equity

#rename and change data types
names(lbank)[22] <- "equity_capital"
lbank$State <- as.factor(lbank$State)
lbank$equity_capital <- as.numeric(lbank$equity_capital)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for total equity capital by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_equity_capital = sum(equity_capital))

#get 2023 Q1 data for total equity capital by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_equity_capital = sum(equity_capital))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_equity_capital_q1_2023 - merged$total_equity_capital_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)

#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_equity_capital_q4_2022 = "2022 Q4",
    total_equity_capital_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_equity_capital_q4_2022, total_equity_capital_q1_2023, diff)
  )

# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Equity Capital After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Gross 1-4 Family Mortgages to Gross Assets"
#| label: tbl-log_mortgages

#rename and change data types
names(lbank)[28] <- "mortgages_to_assets"
lbank$State <- as.factor(lbank$State)
lbank$mortgages_to_assets <- as.numeric(lbank$mortgages_to_assets)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for mortgages to assets by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_mortgages_to_assets = sum(mortgages_to_assets))

#get 2023 Q1 data for mortgages to assets by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_mortgages_to_assets = sum(mortgages_to_assets))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_mortgages_to_assets_q1_2023 - merged$total_mortgages_to_assets_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)

#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_mortgages_to_assets_q4_2022 = "2022 Q4",
    total_mortgages_to_assets_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_mortgages_to_assets_q4_2022, total_mortgages_to_assets_q1_2023, diff)
  )

# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Mortgages to Assets After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Return on Assets"
#| label: tbl-log_roa

#rename and change data types
names(lbank)[97] <- "return_on_assets"
lbank$State <- as.factor(lbank$State)
lbank$return_on_assets <- as.numeric(lbank$return_on_assets)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for return on assets by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_return_on_assets = sum(return_on_assets))

#get 2023 Q1 data for return on assets by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_return_on_assets = sum(return_on_assets))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_return_on_assets_q1_2023 - merged$total_return_on_assets_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)

#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_return_on_assets_q4_2022 = "2022 Q4",
    total_return_on_assets_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_return_on_assets_q4_2022, total_return_on_assets_q1_2023, diff)
  )

# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Return on Assets After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Return on Equity"
#| label: tbl-log_roe

#rename and change data types
names(lbank)[100] <- "return_on_equity"
lbank$State <- as.factor(lbank$State)
lbank$return_on_equity <- as.numeric(lbank$return_on_equity)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for return on equity by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_return_on_equity = sum(return_on_equity))

#get 2023 Q1 data for return on equity by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_return_on_equity = sum(return_on_equity))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_return_on_equity_q1_2023 - merged$total_return_on_equity_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)

#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_return_on_equity_q4_2022 = "2022 Q4",
    total_return_on_equity_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_return_on_equity_q4_2022, total_return_on_equity_q1_2023, diff)
  )

# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Return on Equity After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Total Assets"
#| label: tbl-log_assets

#rename and change data types
names(lbank)[103] <- "total_assets"
lbank$State <- as.factor(lbank$State)
lbank$total_assets <- as.numeric(lbank$total_assets)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for total assets by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_assets = sum(total_assets))

#get 2023 Q1 data for total assets by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_assets = sum(total_assets))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_assets_q1_2023 - merged$total_assets_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)

#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_assets_q4_2022 = "2022 Q4",
    total_assets_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_assets_q4_2022, total_assets_q1_2023, diff)
  )

# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Total Assets After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Total Deposits"
#| label: tbl-log_deposits

#rename and change data types
names(lbank)[106] <- "total_deposits"
lbank$State <- as.factor(lbank$State)
lbank$total_deposits <- as.numeric(lbank$total_deposits)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for total deposits by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_deposits = sum(total_deposits))

#get 2023 Q1 data for total deposits by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_deposits = sum(total_deposits))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_deposits_q1_2023 - merged$total_deposits_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)

#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_deposits_q4_2022 = "2022 Q4",
    total_deposits_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_deposits_q4_2022, total_deposits_q1_2023, diff)
  )

# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Total Deposits After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Log Total Loans & Leases"
#| label: tbl-log_loans

#rename and change data types
names(lbank)[109] <- "total_loans"
lbank$State <- as.factor(lbank$State)
lbank$total_loans <- as.numeric(lbank$total_loans)
lbank$Date <- as.Date(lbank$Date, format = "%m/%d/%Y")

#change date to date format
bank <- lbank %>% 
  mutate(
    year = as.numeric(format(Date, "%Y")),
    month = as.numeric(format(Date, "%m"))) 

#get 2022 Q4 data for total loans by State
q4_2022 <- bank %>% 
  filter(year == 2022, month %in% c(10, 11, 12)) %>% 
  group_by(State) %>% 
  summarize(total_loans = sum(total_loans))

#get 2023 Q1 data for total loans by State
q1_2023 <- bank %>% 
  filter(year == 2023, month %in% c(1, 2, 3)) %>% 
  group_by(State) %>% 
  summarize(total_loans = sum(total_loans))

#merge dataframes together for table
merged <- merge(q4_2022, q1_2023, by = "State", suffixes = c("_q4_2022", "_q1_2023"))

#calculate difference between 2022 and 2023
merged$diff <- merged$total_loans_q1_2023 - merged$total_loans_q4_2022   

#sort descending order
merged <- merged %>% 
  arrange(diff)

#construct gt table
gt_table <- head(merged, 10) %>% 
  gt() %>% 
  cols_label(
    total_loans_q4_2022 = "2022 Q4",
    total_loans_q1_2023 = "2023 Q1",
    diff = "Log Change After Shock"
  ) %>% 
  cols_align(
    align = "left",
    columns = State
  ) %>% 
  cols_align(
    align = "center",
    columns = c(total_loans_q4_2022, total_loans_q1_2023, diff)
  )

# print table 
gt_table

# Add bar graph
ggplot(head(merged, 10), aes(x = reorder(State, diff), y = diff)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Log Change in Total Loans & Leases After Shock",
       x = "State",
       y = "Log Difference (2022 Q4 - 2023 Q1)") +
  theme_minimal()
```